In [1]:
import numpy as np

In [2]:
a= np.array([1,2,3,4])

In [3]:
a

array([1, 2, 3, 4])

#                                Numpy Array Vs Python List

## Benefit # 1: Less Memory

In [4]:
import sys
python_list= list(range(100))
python_list[:5]

[0, 1, 2, 3, 4]

In [5]:
sys.getsizeof(python_list[0])

28

In [6]:
sys.getsizeof(python_list[0])*len(python_list)

2800

In [7]:
numpy_array=np.arange(100)
numpy_array[:5]

array([0, 1, 2, 3, 4])

In [11]:
numpy_array.nbytes

400

as you can see above while numpy array occupies only 400 bytes, the same size list in Python will require 2800 bytes. This shows that nupy array are memory efficient

## Benefit # 2: Speed

In [23]:
import time
Size= 1000000
l1=list(range(Size))
l2=list(range(Size))
start_time=time.time()
l3=[a+b for a, b in zip(l1,l2)]
end_time=time.time()
print("Python list took: ", end_time-start_time)

Python list took:  0.15449881553649902


In [24]:
n1=np.arange(Size)
n2=np.array(Size)
start_time=time.time()
n3=n1+n2
end_time=time.time()
print("Numpy list took: ", end_time-start_time)

Numpy list took:  0.002704143524169922


### Benefit # 3: Convenient Use with Built In Functions

In [26]:
l1= list(range(5))
l2= list(range(5))
l1[:3],l2[:3]

([0, 1, 2], [0, 1, 2])

In [27]:
l1+l2

[0, 1, 2, 3, 4, 0, 1, 2, 3, 4]

In [29]:
l3=[x+y for x , y in zip(l1,l2)]
l3

[0, 2, 4, 6, 8]

In [30]:
n1= np.arange(5)
n2=np.arange(5)
n1,n2

(array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4]))

In [32]:
n3=n1+n2
n3

array([0, 2, 4, 6, 8])

In [34]:
n3=n1*n2
n3

array([ 0,  1,  4,  9, 16])