In [1]:
import numpy as np

### Multiple dimensions in numpy arrays

In [38]:
rev_q1=np.array([10,12,9])
rev_q1.ndim
rev_q1.shape

(3,)

In [3]:
rev=np.array([[10,12,9],[15,11,13]])
rev

array([[10, 12,  9],
       [15, 11, 13]])

In [4]:
rev.ndim

2

### Indexing

In [5]:
# find revenues of first month of second quarter
rev[1,0]

15

In [6]:
# update revenue of first month of second quarter
rev[1,0]=14
rev

array([[10, 12,  9],
       [14, 11, 13]])

### Data type

In [7]:
rev.dtype

dtype('int32')

In [8]:
rev.itemsize

4

In [10]:
rev=np.array([[10,12,9],[15,11,13]],dtype=np.float64)
rev.dtype

dtype('float64')

In [12]:
rev.itemsize

8

### Shorting

In [16]:
np.sort(rev,axis=0)  #column vise sorting

array([[10., 11.,  9.],
       [15., 12., 13.]])

In [17]:
np.sort(rev,axis=1)  #raw vise sorting

array([[ 9., 10., 12.],
       [11., 13., 15.]])

### Zeros, Ones, arange, linspace

In [19]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [23]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [27]:
np.arange(20,30,2)

array([20, 22, 24, 26, 28])

In [28]:
np.linspace(10,50,10)

array([10.        , 14.44444444, 18.88888889, 23.33333333, 27.77777778,
       32.22222222, 36.66666667, 41.11111111, 45.55555556, 50.        ])

### flatten, reshape, min, max

In [29]:
rev

array([[10., 12.,  9.],
       [15., 11., 13.]])

In [39]:
rev.flatten()


array([10., 12.,  9., 15., 11., 13.])

In [42]:
rev.ravel()


array([10., 12.,  9., 15., 11., 13.])

In [45]:
rev.reshape(3,2)

array([[10., 12.],
       [ 9., 15.],
       [11., 13.]])

In [46]:
rev.reshape(2,4)

ValueError: cannot reshape array of size 6 into shape (2,4)

In [47]:
rev.min()

9.0

In [48]:
rev.max()

15.0

### Sum

In [49]:
rev

array([[10., 12.,  9.],
       [15., 11., 13.]])

In [52]:
rev.sum(axis=1) # addding of first raw all and then second raw all

array([31., 39.])

In [53]:
rev.sum(axis=0) #addding of first column all and then second coloms all

array([25., 23., 22.])

In [54]:
for row in rev:
    print("row:",row)

row: [10. 12.  9.]
row: [15. 11. 13.]


In [55]:
b=np.array([1,4,16])
np.sqrt(b)

array([1., 2., 4.])

In [56]:
np.square(b)

array([  1,  16, 256])

In [57]:
np.std(b)

6.48074069840786