In [1]:
import numpy as np

In [2]:
# Sales data for Quarter 1 (Matrix 1)
# Rows represent different products, columns represent different regions

q1 = np.array([
    [200, 220, 250],  # Product A
    [150, 180, 210],  # Product B
    [300, 330, 360]   # Product C
])

q2 = np.array([
    [209, 231, 259],  # Product A
    [155, 192, 222],  # Product B
    [310, 340, 375]   # Product C
])

### Addition, Substraction, Multiplication, Division

In [3]:
# combined sales of Q1 and Q2
q1+q2

array([[409, 451, 509],
       [305, 372, 432],
       [610, 670, 735]])

In [5]:
# sales units growth in q2 compared to q1
q2-q1

array([[ 9, 11,  9],
       [ 5, 12, 12],
       [10, 10, 15]])

In [6]:
# % sales units growth in q2 compared to q1
(q2-q1)*100/q1

array([[4.5       , 5.        , 3.6       ],
       [3.33333333, 6.66666667, 5.71428571],
       [3.33333333, 3.03030303, 4.16666667]])

In [7]:
prices = np.array([
    [10, 12, 11],  # Prices for Product A in different regions
    [8,  9,  10],  # Prices for Product B
    [15, 16, 17]   # Prices for Product C
])

In [10]:
q1_revenue= q1*prices
q1_revenue

array([[2000, 2640, 2750],
       [1200, 1620, 2100],
       [4500, 5280, 6120]])

In [15]:
q1_discount=q1_revenue*0.02
q1_discount

array([[ 40. ,  52.8,  55. ],
       [ 24. ,  32.4,  42. ],
       [ 90. , 105.6, 122.4]])

In [16]:
np.sum(q1_discount)

564.2

In [18]:
net_revenue=q1_revenue-q1_discount
net_revenue

array([[1960. , 2587.2, 2695. ],
       [1176. , 1587.6, 2058. ],
       [4410. , 5174.4, 5997.6]])

### Dot, Cross Product

In [19]:
# first column is square footage, second is bedrooms
features = np.array([
    [2000, 3], # house 1
    [1800, 2]  # house 2
])

weights= np.array([150, 50000])

price= np.dot(features,weights)
price

array([450000, 370000])

In [22]:
c= np.array([1,2,3])
d=np.array([4,5,6])
np.cross(c,d)

array([-3,  6, -3])